apiVersion: v1
kind: Service
metadata:
  name: vproappnode-service
spec:
  type: NodePort
  selector:
    app: vproapp
  ports:
    - protocol: TCP
      port: 30000
      nodePort: 30000
      targetPort: vproapp-port