apiVersion: v1
kind: Pod
metadata:
  name: vproapp-pod
  labels:
    app: vproapp
spec:
  containers:
  - name: vproapp
    image: missawi1/vpro-app:1.0
    ports:
    - name: vproapp-port
      containerPort: 8080
