apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromem-deployment
  labels:
    app: vpromem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromem
  template:
    metadata:
      labels:
        app: vpromem
    spec:
      containers:
      - name: vpromem
        image: memcached:latest
        ports:
        - name: vpromem-port
          containerPort: 11211
