apiVersion: apps/v1
kind: Deployment
metadata:
  name: Db-deployment
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: missawi1/vprodb:1.0
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "admin123"