apiVersion: v1
kind: Service
metadata:
  name: vprodbnode-service
spec:
  type: NodePort
  selector:
    app: vprodb
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30001
      targetPort: vprodb-port