apiVersion: v1
kind: Pod
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  containers:
  - name: vprodb
    image: missawi1/vprodb:1.0
    ports:
    - name: vprodb-port
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "admin123"