version: "3"
services:
  vproapp:
    image: 
    ports:
      -"8080:8080"

  vprodb:
    image: 
    ports:
      -"3306:3306"

  vprongnix:
    image:
    ports:
      - "80:80"

  vpromem:
    image: memcached
    ports:
      - "11211:11211"

  vpromq:
    image: 
    ports: 
      -"5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test