version: "3"
services:
  vprodb:
    image: missawi1/vprodb:1.0
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      
  vproapp: 
    image: missawi1/vpro-app:1.0
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vpromem:
    image: memcached
    ports:
      - "11211:11211"

  vpromq:
    image: rabbitmq
    ports: 
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  vprongnix:
    image: missawi1/vprongnix:1.0
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}