apiVersion: apps/v1
kind: Deployment
metadata:
  name: Db-deployment
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: missawi1/vprodb:1.0
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
          - name: vpro-db-data
            mountPath: /var/lib/mysql
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vproappsecretes
                key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: xxx
            fsType: ext4