apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromem
  labels:
    app: vpromem
spec:
  selector:
    matchLabels:
      app: vpromem
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromem
    spec:
      containers:
      - name: vpromem
        image: memcached
        ports:
          - name: vpromem-port
            containerPort: 11211