kind: Service
apiVersion: v1
metadata:
  name: vproapp-service
spec:
  selector:
    app:  vproapp
  type:  LoadBalancer
  ports:
  - name: name-of-the-port
    port: 80
    targetPort: vproapp-port
    protocol: TCP